from PIL import Image
import numpy as np

COL_BLK = (0, 0, 0)
COL_WHT = (255, 255, 255)
COL_GRY = (167, 169, 172) # L Train
COL_BRO = (153, 102, 51) # J Train
COL_GRN = (108, 190, 69) # G Train

L_BULLET: Image = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK],
      [COL_BLK, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_BLK, COL_GRY, COL_GRY, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_GRY, COL_GRY, COL_BLK],
      [COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

J_BULLET: Image = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK],
      [COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BLK],
      [COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BLK, COL_BRO, COL_BRO, COL_WHT, COL_WHT, COL_WHT, COL_BRO, COL_BRO, COL_BRO, COL_BLK],
      [COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

G_BULLET: Image = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_BLK],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

UNKNOWN_BULLET: Image = Image.new('RGB', (10, 10))