from PIL import Image
import numpy as np

VALID_STOP_IDS = {
  "1",
  "2",
  "3",
  "4",
  "5",
  "5X", # Rush hour peak direction express
  "6",
  "6X", # Weekday peak direction express
  "7",
  "7X", # Rush hour peak direction express
  "GS", # 42nd street shuttle
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "FX", # Rush hour peak direction express
  "FS", # Franklin avenue shuttle
  "G",
  "H", # Rockaway park shuttle
  "J",
  "Z",
  "L",
  "M",
  "N",
  "Q",
  "W",
  "R",
  "SI", # Staten island railway
}

COL_BLK = (0, 0, 0)
COL_WHT = (255, 255, 255)
COL_GRY = (167, 169, 172) # L Train
COL_BRO = (153, 102, 51) # J Train
COL_GRN = (108, 190, 69) # G Train

L_BULLET: Image = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK],
      [COL_BLK, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_BLK, COL_GRY, COL_GRY, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_GRY, COL_GRY, COL_BLK],
      [COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

J_BULLET: Image = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK],
      [COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BLK],
      [COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BLK, COL_BRO, COL_BRO, COL_WHT, COL_WHT, COL_WHT, COL_BRO, COL_BRO, COL_BRO, COL_BLK],
      [COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

G_BULLET: Image = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_BLK],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

UNKNOWN_BULLET: Image = Image.new('RGB', (10, 10))