from PIL import Image
import numpy as np

VALID_LINE_IDS = {
  "1",
  "2",
  "3",
  "4",
  "5",
  "5X", # Rush hour peak direction express
  "6",
  "6X", # Weekday peak direction express
  "7",
  "7X", # Rush hour peak direction express
  "GS", # 42nd street shuttle
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "FX", # Rush hour peak direction express
  "FS", # Franklin avenue shuttle
  "G",
  "H", # Rockaway park shuttle
  "J",
  "Z",
  "L",
  "M",
  "N",
  "Q",
  "W",
  "R",
  "SI", # Staten island railway
}

COL_BLK = (0, 0, 0)
COL_WHT = (255, 255, 255)
COL_RED = (238, 53, 46) # 7th Av Trains
COL_GRN = (0, 147, 60) # Lex Trains
COL_PUR = (185, 51, 173) # 7 Train
COL_GRY = (167, 169, 172) # L Train
COL_BRO = (153, 102, 51) # J Train
COL_LME = (108, 190, 69) # G Train

L_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK],
      [COL_BLK, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_GRY, COL_GRY, COL_GRY, COL_WHT, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY],
      [COL_BLK, COL_GRY, COL_GRY, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_GRY, COL_GRY, COL_BLK],
      [COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRY, COL_GRY, COL_GRY, COL_GRY, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

J_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK],
      [COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BLK],
      [COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BRO, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_WHT, COL_BRO, COL_BRO, COL_BRO],
      [COL_BLK, COL_BRO, COL_BRO, COL_WHT, COL_WHT, COL_WHT, COL_BRO, COL_BRO, COL_BRO, COL_BLK],
      [COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_BRO, COL_BRO, COL_BRO, COL_BRO, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

G_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_LME, COL_LME, COL_LME, COL_LME, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME, COL_BLK],
      [COL_BLK, COL_LME, COL_LME, COL_LME, COL_WHT, COL_WHT, COL_WHT, COL_LME, COL_LME, COL_BLK],
      [COL_LME, COL_LME, COL_LME, COL_WHT, COL_LME, COL_LME, COL_WHT, COL_LME, COL_LME, COL_LME],
      [COL_LME, COL_LME, COL_LME, COL_WHT, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME],
      [COL_LME, COL_LME, COL_LME, COL_WHT, COL_LME, COL_WHT, COL_WHT, COL_LME, COL_LME, COL_LME],
      [COL_LME, COL_LME, COL_LME, COL_WHT, COL_LME, COL_LME, COL_WHT, COL_LME, COL_LME, COL_LME],
      [COL_BLK, COL_LME, COL_LME, COL_WHT, COL_WHT, COL_WHT, COL_LME, COL_LME, COL_LME, COL_BLK],
      [COL_BLK, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME, COL_LME, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_LME, COL_LME, COL_LME, COL_LME, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

IRT_1_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_RED, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_RED, COL_RED],
      [COL_RED, COL_RED, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_RED, COL_RED],
      [COL_RED, COL_RED, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_RED, COL_RED],
      [COL_RED, COL_RED, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_RED, COL_RED],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

IRT_2_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_RED, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_RED],
      [COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_RED],
      [COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_RED, COL_RED],
      [COL_RED, COL_RED, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED],
      [COL_BLK, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_BLK],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

IRT_3_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_BLK, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_BLK],
      [COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_RED],
      [COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_RED, COL_RED],
      [COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_RED],
      [COL_RED, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_WHT, COL_RED, COL_RED, COL_RED],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_WHT, COL_WHT, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_RED, COL_RED, COL_RED, COL_RED, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

IRT_4_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_BLK],
      [COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

IRT_5_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_BLK],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

IRT_6_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

IRT_7_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_BLK],
      [COL_BLK, COL_PUR, COL_PUR, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_PUR, COL_PUR, COL_BLK],
      [COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_PUR],
      [COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_PUR, COL_PUR],
      [COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_PUR, COL_PUR],
      [COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR],
      [COL_BLK, COL_PUR, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_BLK],
      [COL_BLK, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

EXP_5_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

EXP_6_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_BLK, COL_BLK],
      [COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_GRN, COL_GRN],
      [COL_GRN, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_GRN],
      [COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_WHT, COL_GRN, COL_GRN, COL_BLK],
      [COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_WHT, COL_WHT, COL_GRN, COL_GRN, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_BLK, COL_GRN, COL_GRN, COL_BLK, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)

EXP_7_BULLET = Image.fromarray(
  np.array(
    [
      [COL_BLK, COL_BLK, COL_BLK, COL_BLK, COL_PUR, COL_PUR, COL_BLK, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_PUR, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_PUR, COL_BLK, COL_BLK],
      [COL_BLK, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_BLK],
      [COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_PUR, COL_PUR],
      [COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_PUR, COL_PUR],
      [COL_BLK, COL_PUR, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_BLK],
      [COL_BLK, COL_BLK, COL_PUR, COL_PUR, COL_WHT, COL_PUR, COL_PUR, COL_PUR, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_PUR, COL_PUR, COL_PUR, COL_PUR, COL_BLK, COL_BLK, COL_BLK],
      [COL_BLK, COL_BLK, COL_BLK, COL_BLK, COL_PUR, COL_PUR, COL_BLK, COL_BLK, COL_BLK, COL_BLK],
    ],
    dtype=np.int8
  ),
  'RGB'
)
